config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  root to: 'homes#top'
  resources :resipis do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
  get 'search' => 'resipis#search'
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :resipi
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :resipi
  
end

app/models/resipi.rb
class Resipi < ApplicationRecord
  
  belongs_to :user
  attachment :image
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :name, presence: true
  validates :image, presence: true
  validates :material, presence: true
  validates :introduction, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.search(keyword)
    where(["name like? OR material like?", "%#{keyword}%", "%#{keyword}%"])
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :resipis, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    resipi = Resipi.find(params[:resipi_id])
    comment = current_user.comments.new(comment_params)
    comment.resipi_id = resipi.id
    comment.save
    redirect_to resipi_path(resipi)
  end

  def destroy
    Comment.find_by(id: params[:id]).destroy
    redirect_to resipi_path(params[:resipi_id])
  end
  
  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    resipi = Resipi.find(params[:resipi_id])
    favorite = current_user.favorites.new(resipi_id: resipi.id)
    favorite.save
    redirect_to resipi_path(resipi)
  end

  def destroy
    resipi = Resipi.find(params[:resipi_id])
    favorite = current_user.favorites.find_by(resipi_id: resipi.id)
    favorite.destroy
    redirect_to resipi_path(resipi)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
end

app/controllers/resipis_controller.rb
class ResipisController < ApplicationController
  
  def new
    @resipi = Resipi.new
  end

  def create
    @resipi = Resipi.new(resipi_params)
    @resipi.user_id = current_user.id
    if @resipi.save
      redirect_to resipis_path
    else
      render :new
    end
  end

  def index
    @resipis = Resipi.page(params[:page]).reverse_order
  end

  def show
    @resipi = Resipi.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    @resipi = Resipi.find(params[:id])
    @resipi.destroy
    redirect_to resipis_path
  end
  
  def search
    @resipis = Resipi.search(params[:keyword])
    @keyword = params[:keyword]
    render "index"
  end
  
  private

  def resipi_params
    params.require(:resipi).permit(:name, :image, :material, :introduction)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @resipis = @user.resipis.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/resipis_helper.rb
module ResipisHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class="text-center">
 <div calss="row">
 <br><br><br>
 
 <p>ようこそmesiteroへ</p>
 <p>ここでは、自分で考えたレシピやアレンジを公開し様々なユーザーと交流するサイトです。</p>
 <p>もちろん公開されているレシピを見るだけでも可能です。</p>
 
  <%= link_to "レシピ一覧", resipis_path %>
  <br><br><br>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>mesitero</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body class="back">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
      <!--ロゴ-->
      <div class="p-6">
        <%= link_to root_path do %>
        <%= image_tag "logo.png", :size => '280x100' %>
        <% end %>
      </div>
      <!--検索機能-->
      <div class="text-center">
        <%= form_with url: search_path, method: :get, local: true do |f| %>
        <%= f.text_field :keyword, value: @keyword %>
        <%= f.submit "検索" %>
        <% end %>
      </div>
      <div class="pull-right">
       <% if user_signed_in? %>
       <!--レシピ投稿-->
        <%= link_to new_resipi_path do %>
        <%= image_tag "new_resipi.png", :size => '100x100' %>
        <% end %>
       <!--マイページ-->
         <%= link_to user_path(current_user.id) do %>
         <%= image_tag "mypage.png", :size => '100x100' %>
         <% end %>
       <!--ログアウト-->
        <%= link_to destroy_user_session_path, method: :delete do %>
        <%= image_tag "log_out.png", :size => '100x100' %>
        <% end %>
       <% else %>
       <!--会員登録-->
        <%= link_to new_user_registration_path do %>
        <%= image_tag "new_user.png", :size => '100x100' %>
        <% end %>
       <!--ログイン-->
        <%= link_to new_user_session_path do %>
        <%= image_tag "log_in.png", :size => '100x100' %>
        <% end %>
       <% end %>
      </div>
    </div>
  </nav>
    <%= yield %>
</body>
<footer class="footer" >
  <div class="row">
    <div class="mx-auto">
    <br><br><br>
    <p>© 2021 mesitero CopyRight Infratop.inc</p>
    </div>
  </div>
</footer>
</html>

app/views/resipis/index.html.erb
<div class="container-fluid">
  <div calss="row">
 　  <% @resipis.each do |resipi| %>
　  　<div class="col-md-3 px-4 shadow-lg my-5"><br>
　　  　<%= attachment_image_tag resipi, :image, format: 'png', fallback: "no_image.jpg", size: "420x300" %><br>
　　    <p>
　　  　<%= attachment_image_tag @user, :profile_image, format: 'png', fallback: "no_image.jpg", size: "60x60" %>
        <%= link_to resipi_path(resipi.id) do %>
　　  　料理名：<%= resipi.name %>
　　  　</p>
　　  　<% end %>
　　  　<br>
　  　　投稿者：<%= resipi.user.name %>
　　  　<%= link_to "#{resipi.comments.count} コメント", resipi_path(resipi.id) %><br>
　  　</div>
    <% end %>
  </div>
</div>

app/views/resipis/new.html.erb
<div class="row">
  <div class="mx-auto">
    <h1>レシピ投稿</h1>
    <% if @resipi.errors.any? %>
     <%= @resipi.errors.count %>件のエラーが発生しました
     <% @resipi.errors.full_messages.each do |message| %>
      <%= message %>
     <% end %>
    <% end %>
    <%= form_with model: @resipi, local:true do |f| %>
     <h4>料理画像</h4>
     <%= f.attachment_field :image %>
     <p></p>
     <h4>レシピ名</h4>
     <%= f.text_field :name, :size=>"40x10" %>
     <p></p>
     <h4>材料</h4>
     <%= f.text_area :material, :size=>"60x7" %>
     <p></p>
     <h4>作り方</h4>
     <%= f.text_area :introduction, :size=>"60x10" %>
     <p></p>
     <%= f.submit 'レシピを投稿する' %>
   <% end %>
  </div>
</div>

app/views/resipis/show.html.erb
<div class="container">
 <div class="row">
  <div class="col-lg-6"><br><br>
    <%= attachment_image_tag @resipi,:image, format: 'jpeg', fallback: "no_image.jpg", size: "920x540"  %>
  </div>
 </div>
</div>

<div class="container">
 <div class="row">
  <div class="col-lg-6"><br><br>
    料理名：<%= @resipi.name %> 
    <!--いいね機能-->
    <% if @resipi.favorited_by?(current_user) %>
      <p>
        <%= link_to resipi_favorites_path(@resipi), method: :delete do %>
          ♥<%= @resipi.favorites.count %> いいね
        <% end %>
      </p>
      <% else %>
      <p>
        <%= link_to resipi_favorites_path(@resipi), method: :post do %>
          ♡<%= @resipi.favorites.count %> いいね
        <% end %>
      </p>
    <% end %>
    <!--ここまで-->
    <p>投稿者：<%= @resipi.user.name %></p>
    <p>投稿日時：<%= @resipi.created_at.strftime('%Y/%m/%d') %></p>
    <p>材料：<%= @resipi.material %></p>
    <p>作り方：<%= @resipi.introduction %></p>
    <% if @resipi.user == current_user %>
      <%= link_to "削除", resipi_path(@resipi), method: :delete %>
    <% end %>
  </div>
 </div>
</div>

<div class="container">
 <div class="row">
  <div class="col-lg-6"><br>
   <p>コメント件数：<%= @resipi.comments.count %></p>
   <% @resipi.comments.each do |comment| %>
    <%= attachment_image_tag comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
     <%= comment.user.name %>
     <%= comment.created_at.strftime('%Y/%m/%d') %><%= comment.comment %>
     <% if comment.user == current_user %>
     <div>
       <%= link_to "削除", resipi_comment_path(comment.resipi, comment), method: :delete %>
     </div>
     <% end %>
   <% end %>
  </div>
 </div>
</div>

<div class="container">
 <div class="row">
  <div class="col-lg-6"><br>
   <%= form_with(model:[@resipi, @comment], local: true) do |f| %>
      <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", :size=>"60x10" %>
      <%= f.submit "コメントする" %>
   <% end %>
  </div>
 </div>
</div>

app/views/users/edit.html.erb
<div class="text-center">
 <div calss="row">
  <h2>プロフィール編集</h2><br>
  <%= form_with model:@user, local:true do |f| %>
    <%= attachment_image_tag @user,:profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "200x200" %><br><br>
    <label for="inputImage"></label><br><br>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %><br><br>
    <label for="inputName">ニックネーム</label><br>
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%><br><br>

    <%= f.submit "変更を保存" %>
  <% end %>
 </div>
</div>

app/views/users/show.html.erb
<div class="row">
 <div class="mx-auto">
   <br><br>
    <%= attachment_image_tag @user,:profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "200x200" %>
    <p><br>
      <h4>ニックネーム:<%= @user.name %></h4>
    </p><br>
    <% if @user.id == current_user.id %>
      <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
    <% end %>
 </div>
</div>

<div class="container-fluid">
 <div calss="row">  
 <h3>投稿レシピ一覧</h3>
  <% @resipis.each do |resipi| %>
     <div class="col-md-2 px-4 shadow-lg my-5">
      <%= attachment_image_tag resipi, :image, format: 'jpeg', fallback: "no_image.jpg", size: "240x200"   %>
 　　　　 <%= link_to resipi_path(resipi.id) do %>
 　　　 　 <p>料理名:<%= resipi.name %></p>
       <br>
      <% end %>
      </div>
     <% end %>
  <%= paginate @resipis %>
 </div>
</div>